# Generated by Django 5.1.7 on 2025-03-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_dish_images_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish_images',
            name='name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
